unit TestuProduto;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework,  uProduto, uDmCadastro;

type
  // Test methods for class TProduto

  TestTProduto = class(TTestCase)
  strict private
    FProduto: TProduto;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGravar;
    procedure TestExcluir;
    procedure TestConsultar;
  end;

implementation

procedure TestTProduto.SetUp;
begin
  FProduto := TProduto.Create;
end;

procedure TestTProduto.TearDown;
begin
  FProduto.Free;
  FProduto := nil;
end;

procedure TestTProduto.TestGravar;
begin
  FProduto.setId(999);
  FProduto.setCodigo('Cod999');
  FProduto.SetNome('Teste');
  FProduto.setDescricao('Teste');
  FProduto.setValorUnitario(10);
  FProduto.setPeso(1);
  FProduto.setAltura(2);
  FProduto.Gravar;

  // TODO: Validate method results
end;

procedure TestTProduto.TestExcluir;
begin
  FProduto.Excluir;
  // TODO: Validate method results
end;

procedure TestTProduto.TestConsultar;
var
  pId: Integer;
begin
  // TODO: Setup method call parameters
  FProduto.Consultar(pId);
  // TODO: Validate method results
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTProduto.Suite);
end.

